<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)' == ''">
		<VersionNumber>3.0-debug</VersionNumber>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>
  <PropertyGroup>
    <PackageId>SanteDB.Messaging.HL7</PackageId>
    <Title>SanteDB HL7 Messaging</Title>
    <Version>$(VersionNumber)</Version>
    <Description>Allows SanteDB iCDR to accept HL7 messages.</Description>
    <Authors>SanteSuite Contributors</Authors>
    <PackageTags>SanteDB</PackageTags>
    <RepositoryUrl>https://github.com/santedb/santedb-hl7</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
	    <Product>SanteDB</Product>
    <Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
    <Company>SanteSuite Contributors</Company>
    <PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
    <PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
  </PropertyGroup>   
  <ItemGroup>
    <EmbeddedResource Include="ParameterMap.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\SanteDB.licenseheader">
      <Link>SanteDB.licenseheader</Link>
    </None>
    <None Include="Data\*.dataset">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Choose>
    <When Condition="$(SolutionName.Contains('-nuget'))">
      <ItemGroup>
        <PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
        <PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
        <PackageReference Include="SanteDB.Docker.Core" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Client" Version="$(VersionNumber)" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="..\..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
        <ProjectReference Include="..\..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
        <ProjectReference Include="..\..\santedb-docker\SanteDB.Docker.Core\SanteDB.Docker.Core.csproj" />
				<ProjectReference Include="..\..\santedb-dc-core\SanteDB.Client\SanteDB.Client.csproj" />
      </ItemGroup>
    </Otherwise>
  </Choose>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="[13.0.4,13.1)" />
    <PackageReference Include="nhapi" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="applet\**\*" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Docker\Hl7Feature.xml" />
  </ItemGroup>
</Project>
